source 'http://git.houyicloud.com/ios/hyspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'HYModuleB_Example' do
    pod 'HYModuleB', :path => '../'
    pod 'HYModuleA'
end
